project_id = "gqfvpfwuljufbicetxni"

[functions.delete-account]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.unlock-photo]
verify_jwt = false
